{{- $platformConfig := (lookup "v1" "ConfigMap" .Values.namespace "agentic-platform-config") -}}
{{- if $platformConfig -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "mcp.name" . }}-secret
  namespace: {{ include "mcp.namespace" . }}
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: {{ include "mcp.name" . }}-secretstore
    kind: SecretStore
  target:
    name: {{ include "mcp.name" . }}-agent-secret
    creationPolicy: Owner
  data:
    - secretKey: "LITELLM_KEY"
      remoteRef:
        key: {{ index $platformConfig.data .Values.agentSecret.configKey }}
        property: "LITELLM_KEY"
{{- end }}
