apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "mcp.name" . }}-secretstore
  namespace: {{ include "mcp.namespace" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ include "mcp.parameterStoreRegion" . }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
