{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "mcp.namespace" . }}
  labels:
    app: {{ include "mcp.name" . }}
    component: mcp-server
  {{- if include "mcp.irsaRoleArn" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "mcp.irsaRoleArn" . }}
  {{- end }}
{{- end }}
